pipeline{
    agent any
        stages{
            stage("Hello"){
                steps{
                    echo "Hello, this is my first pipeline"
                }
            }
            stage("clone"){
                steps{
                    echo "Clone repository"
                }
            }
            stage("Run build"){
                steps{
                    echo "running code for errors"
                }
            }
            stage("Testing"){
                steps{
                    echo "testing code"
                }
            }
        }
}

